# strongswan.conf minimal pour le lab : charon + plugin vici sur un socket dédié
# (placé dans un volume partagé avec le backend).
charon {
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf
        vici {
            socket = unix:///vicirun/charon.vici
        }
    }
    filelog {
        stderr {
            default = 1
            ike = 1
            cfg = 1
            knl = 1
        }
    }
}
